#!/bin/sh
env/bin/flake8 ccguard/ccguard.py
env/bin/black --check ccguard/*.py
env/bin/pytest --cov-report xml --cov ccguard
env/bin/python ccguard/ccguard.py --html coverage.xml --repository ccguard
