#!/bin/sh
set -e
env/bin/black --check ccguard/*.py
env/bin/flake8 ccguard/*.py
env/bin/pytest --cov-report xml --cov ccguard
env/bin/python ccguard/ccguard.py --html coverage.xml --consider-uncommitted-changes --debug
